[workspace]
resolver = "3"
members = ["bootloader", "font"]

[workspace.dependencies]
font = { path = "font" }

[workspace.lints]
rust.elided_lifetimes_in_paths = "deny"

clippy.missing_safety_doc = "allow"

[profile.dev]
opt-level = 3
lto = "thin"
